accounts/urls.py
from django.urls import path , include
from . import views


app_name="accounts"

urlpatterns = [

    path('home',views.home),
    path('register',views.registerPage,name='register'),
    path('login',views.loginPage,name='login'),
    path('logout',views.logoutUser,name='logout'),
    path('myaccount', views.MyAccount, name='myaccount'),
    path('myadds', views.Myadds, name='myadds'),




]

adds/urls.py
from django.urls import path , include
from . import views

app_name = 'list'

urlpatterns = [

    path('',views.list, name='list'),
    path('Sections',views.SectionsModel, name='sections'),
    path('create_add',views.create_ad,name='create_ad'),
    path('update_add/<int:id>',views.update_add,name='update_add'),
    path('<int:id>',views.detail,name='details'),
    path('sub/<title>',views.sub_1,name='sub_1'),
    path('land',views.sub_land,name='land'),




]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from adds import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adds.urls', namespace='list')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

]
urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

ad_detail/models.py
from django.db import models

# Create your models here.

adds/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
from django.core.validators import MinLengthValidator
from django.core.validators import RegexValidator
city_names = (
    ('جدة','جدة'),
    ('الرياض', 'الرياض'),
)
bre_b7re = (
    ('بري','بري'),
    ('بحري', 'بحري'),
)
bre = (
    ('شاليهات','شاليهات'),
    ('مخيمات', 'مخيمات'),
    ('قوارب صيد', 'قوارب صيد'),
    ('قوارب نزهه', 'قوارب نزهه'),
    ('غوص', 'غوص'),
    ('العاب مائية', 'العاب مائية'),
    ('مخيمات شاطئية', 'مخيمات شاطئية'),
    ('دراجات', 'دراجات'),
    ('متاحف', 'متاحف'),
)
def image_upload(instance,filename):
    imagename , extension = filename.split(".")
    return "menu/%s.%s"%(instance.id,extension)
# Create your models here.
class a8sam1(models.Model):  # table
    title = models.CharField(max_length=15, choices=bre)
    namex =  models.CharField(max_length=100)  # column
    icon = models.ImageField(upload_to=image_upload)
    def __str__(self):
        return self.title
    pass

class add_detail(models.Model):  # table
    username = models.CharField(max_length=10,default='')
    title = models.CharField(max_length=50)  # column
    description = models.TextField(max_length=1000)
    price = models.CharField(max_length=5)
    phone = models.CharField(max_length=10,default='',validators=[RegexValidator(regex='^.{10}$', message='Length has to be 10', code='nomatch')])
    image = models.ImageField(upload_to=image_upload)
    city = models.CharField(max_length=15, choices=city_names)
    cate = models.CharField(max_length=15, choices=bre)
    updated_at = models.DateTimeField(auto_now_add=True)
    img1 = models.ImageField(upload_to=image_upload,blank=True)
    img2 = models.ImageField(upload_to=image_upload,blank=True)
    img3 = models.ImageField(upload_to=image_upload,blank=True)
    img4 = models.ImageField(upload_to=image_upload,blank=True)
    def __str__(self):
        return self.title
    pass

home/models.py
from django.db import models

# Create your models here.

login/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render , redirect , HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .form import CreateUserForm
from .models import *
import adds
from adds.models import *

from django.contrib import messages
from django.contrib.auth import authenticate ,login , logout
from django.contrib.auth.decorators import login_required
# Create your views here.
def home (request):
    pass
def registerPage (request):
    if request.user.is_authenticated:
        return redirect('list:list')
    form = CreateUserForm()

    if request.method == "POST":

        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request,"تم انشاء حساب " + user)
            return redirect('accounts:login')
    context = {'form':form}
    return render(request,'register1.html',context)
def loginPage(request):
    if request.user.is_authenticated:
        return redirect('list:list')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password =request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('list:list')
            else:
                messages.info(request, 'Username OR password is incorrect')

        context = {}
        return render(request, 'login1.html', context)

def logoutUser(request):
	logout(request)
	return redirect('list:list')


def MyAccount (request):
    if request.user.is_authenticated:

        return render(request, 'myaccount.html')

def Myadds (request):
    if request.user.is_authenticated:
        addd1 = add_detail.objects.filter(username=request.user)
        addd2 = a8sam1.objects.all()
        context = {'ad': addd1, 'tt': addd2}
        return render(request, 'myadds.html',context)

ad_detail/views.py
from django.shortcuts import render

# Create your views here.

adds/views.py
from django.shortcuts import render , redirect
from .models import *
from django.contrib.auth.decorators import login_required
# Create your views here.
##@login_required(login_url='accounts:login')
from .form import adForm


def list(request):
    addd1 = add_detail.objects.all()
    addd2 = a8sam1.objects.all()
    context = {'ad': addd1 , 'tt': addd2}
    return render(request,'list.html',context)
    pass

def SectionsModel(request):
    addd2 = a8sam1.objects.all()
    context = {'tt': addd2}
    return render(request,'Sections.html',context)
    pass
def create_ad(request):
    if request.user.is_authenticated:
        pass
    else:
        return redirect('accounts:login')
    form = adForm()
    user = request.user
    if request.method == 'POST':
        print('form-data :',request.POST)
        updated_request = request.POST.copy()
        updated_request.update({'username': user})
        form = adForm(updated_request, request.FILES)


       # print(form['username'].value(),'======',user)
        if form.is_valid():
            form.save()
            form.user = request.user
            print('ad created !!')

            return redirect('/')
        else:
            print('add not create')


    context = {'form': form}
    return render(request,'create_ad.html',context)
    pass
def detail(request,id):

    detail = add_detail.objects.get(id=id)

    context= {'ad_details': detail}
    return render(request,'dd_detail.html',context)

    pass



def sub_1(request,title):
    addd1 = add_detail.objects.filter(cate=title)
    addd2 = a8sam1.objects.all()
    context = {'ad': addd1, 'tt': addd2}
    return render(request, 'list.html', context)
    pass

def sub_land(request):
    addd1 = add_detail.objects.filter(cate='مخيمات')
    addd2 = a8sam1.objects.all()
    context = {'ad': addd1, 'tt': addd2}
    return render(request, 'list.html', context)
    pass
def myadds_view(request):
    addd1 = add_detail.objects.filter(cate='مخيمات')
    addd2 = a8sam1.objects.all()
    context = {'ad': addd1, 'tt': addd2}
    return render(request, 'list.html', context)
    pass
def update_add(request,id):
    if request.user.is_authenticated:
        pass
    else:
        return redirect('accounts:login')
    add_21 = add_detail.objects.get(id=id)

    user = request.user
    form = adForm(instance=add_21)

    context = {'form': form}
    return render(request,'ad_update.html',context)
    pass

home/views.py
from django.shortcuts import render

# Create your views here.

login/views.py
from django.shortcuts import render

# Create your views here.

adds/templates/Sections.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
 <link
      rel="stylesheet"
      href="https://unpkg.com/swiper/swiper-bundle.min.css"
    />

    <!-- Demo styles -->
 <link rel="stylesheet" href="{% static 'css/swp.css' %}">
  </head>
<div class="nn-con">
<div class="con sec-box-page" >
{% for x in tt %}
            <div class="gsm-box" onclick="location.href='{% url  'list:sub_1' x.title %}';">
            <div class="icon"><img src={{x.icon.url}} loading="lazy" alt="" class="image-2"></div>
            <div class="icontext">
            <div class="text-block-8">{{x.title}} </div>
            </div>
            </div>
{%endfor%}


  </div>
</div>
{% endblock body %}

adds/templates/ad_update.html
{% extends 'base.html' %}
{% block body %}
{% load static %}


        <link rel="stylesheet" href="{%  static 'css/create_add.css' %}">
      <div class="container">

        <form action="" method="post" enctype="multipart/form-data" >
            {% csrf_token %}



        <div class="Text-box" style="">
          <div class="sub-header">
            <p>تعديل الاعلان <i class="fas fa-plus"></i> </p>
          </div>
          <div class="text-title">    <p>عنوان الاعلان </p>  <i class="fas fa-angle-left"> </i>  </div>


             <input  required="" style="direction: rtl;" type="text" class="form-control" name="title" id="id_title" placeholder="اكتب عنوان الاعلان">


          <div class="text-title">  <p>وصف الاعلان </p>  <i class="fas fa-align-justify"></i></div>


            <div class="input-group">

        <textarea required=""  style="direction: rtl;" name="description" id="id_description"class="form-control" aria-label="With textarea"></textarea>
        </div>

          <div class="black-line "></div>
          <div class="text-title">  السعر      <i class="far fa-money-bill-alt"></i></div>
          <div class="text-box2" dir="rtl" >
                <div class="input-group mb-3">
                  <span class="input-group-text">ريال</span>
             <input type="text" name="price" maxlength="5" required="" id="id_price">
             <span class="input-group-text">.00</span>
                </div>
            </div>
            <!-- -------------------------->
                    <div class="text-title">المدينة <i class="fas fa-map-marker-alt"></i></div>
            <select  required="" name="city" required="" id="id_city" class="form-select" aria-label="Default select example">
    <option></option>
                <option style="" value="جدة">جدة </option>
                <option style="" value="الرياض">الرياض </option>
            </select>
            <!-- -------------------------->
                  <!-- -------------------------->
                    <div class="text-title">القسم <i class="fas fa-map-marker-alt"></i></div>
            <select  required="" name="cate" required="" id="id_cate" class="form-select" aria-label="Default select example">
                 <option></option>
                <option value="شاليهات">شاليهات</option>
                <option value="مخيمات">مخيمات</option>
                <option value="قوارب صيد">قوارب صيد</option>
                <option value="قوارب نزهة">قوارب نزهة</option>
            </select>

            <!-- -------------------------->


            <div class="text-title">رقم التواصل <i class="fas fa-phone"></i> </div>
            <div class="text-box2" dir="rtl" >
            <div class="input-group mb-3">

              <input  required="" name="phone"  maxlength="10" minlength="10" id="id_phone" type="text" class="form-control" aria-label="ادخل رقم الجوال ">
             <span class="input-group-text">+966</span>
                </div>




            </div>

          <div class="black-line "></div>

          <div class="text-title">رفع الصور   </div>

          <div class="text-title"> صورة الغلاف   </div>
                <div class="input-group mb-3 drtl" style="direction: rtl;" >
                 <input  required="" type="file" class="form-control" name="image" id="id_image" >
                 </div>
               <div class="text-title"> صور اخرى </div>
                <div class="input-group mb-3 drtl" style="direction: rtl;" >
                 <input title="dd" type="file" class="form-control"name="img1" id="id_img1" >
                 </div>
              <div class="input-group mb-3 drtl" style="direction: rtl;" >
                 <input title="dd" type="file" class="form-control" name="img2" id="id_img2" >
                 </div>
              <div class="input-group mb-3 drtl" style="direction: rtl;" >
                 <input title="dd" type="file" class="form-control"name="img3"  id="id_img3" >
                 </div>
              <div class="input-group mb-3 drtl" style="direction: rtl;" >
                 <input title="dd" type="file" class="form-control" name="img4" id="id_img4" >
                 </div>




          <input class="sub-btn" value="تعديل " type="submit"></input>
        </div>
        </form>

    </div>



{% endblock body %}

adds/templates/create_ad.html
{% extends 'base.html' %}
{% block body %}
{% load static %}


        <link rel="stylesheet" href="{%  static 'css/create_add.css' %}">
      <div class="container">

        <form action="" method="post" enctype="multipart/form-data" >
            {% csrf_token %}



        <div class="Text-box" style="">
          <div class="sub-header">
            <p> إعلان جديد <i class="fas fa-plus"></i> </p>
          </div>
          <div class="text-title">    <p>عنوان الاعلان </p>  <i class="fas fa-angle-left"> </i>  </div>


             <input  required="" style="direction: rtl;" type="text" class="form-control" name="title" id="id_title" placeholder="اكتب عنوان الاعلان">


          <div class="text-title">  <p>وصف الاعلان </p>  <i class="fas fa-align-justify"></i></div>


            <div class="input-group">

        <textarea required=""  style="direction: rtl;" name="description" id="id_description"class="form-control" aria-label="With textarea"></textarea>
        </div>

          <div class="black-line "></div>
          <div class="text-title">  السعر      <i class="far fa-money-bill-alt"></i></div>
          <div class="text-box2" dir="rtl" >
                <div class="input-group mb-3">
                  <span class="input-group-text">ريال</span>
             <input type="text" name="price" maxlength="5" required="" id="id_price">
             <span class="input-group-text">.00</span>
                </div>
            </div>
            <!-- -------------------------->
                    <div class="text-title">المدينة <i class="fas fa-map-marker-alt"></i></div>
            <select  required="" name="city" required="" id="id_city" class="form-select" aria-label="Default select example">
    <option></option>
                <option style="" value="جدة">جدة </option>
                <option style="" value="الرياض">الرياض </option>
            </select>
            <!-- -------------------------->
                  <!-- -------------------------->
                    <div class="text-title">القسم <i class="fas fa-map-marker-alt"></i></div>
            <select  required="" name="cate" required="" id="id_cate" class="form-select" aria-label="Default select example">
                 <option></option>
                <option value="شاليهات">شاليهات</option>
                <option value="مخيمات">مخيمات</option>
                <option value="قوارب صيد">قوارب صيد</option>
                <option value="قوارب نزهة">قوارب نزهة</option>
            </select>

            <!-- -------------------------->


            <div class="text-title">رقم التواصل <i class="fas fa-phone"></i> </div>
            <div class="text-box2" dir="rtl" >
            <div class="input-group mb-3">

              <input  required="" name="phone"  maxlength="10" minlength="10" id="id_phone" type="text" class="form-control" aria-label="ادخل رقم الجوال ">
             <span class="input-group-text">+966</span>
                </div>




            </div>

          <div class="black-line "></div>

          <div class="text-title">رفع الصور   </div>

          <div class="text-title"> صورة الغلاف   </div>
                <div class="input-group mb-3 drtl" style="direction: rtl;" >
                 <input  required="" type="file" class="form-control" name="image" id="id_image" >
                 </div>
               <div class="text-title"> صور اخرى </div>
                <div class="input-group mb-3 drtl" style="direction: rtl;" >
                 <input title="dd" type="file" class="form-control"name="img1" id="id_img1" >
                 </div>
              <div class="input-group mb-3 drtl" style="direction: rtl;" >
                 <input title="dd" type="file" class="form-control" name="img2" id="id_img2" >
                 </div>
              <div class="input-group mb-3 drtl" style="direction: rtl;" >
                 <input title="dd" type="file" class="form-control"name="img3"  id="id_img3" >
                 </div>
              <div class="input-group mb-3 drtl" style="direction: rtl;" >
                 <input title="dd" type="file" class="form-control" name="img4" id="id_img4" >
                 </div>




          <input class="sub-btn" value="أضافة الاعلان " type="submit"></input>
        </div>
        </form>

    </div>



{% endblock body %}

adds/templates/list.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
 <link
      rel="stylesheet"
      href="https://unpkg.com/swiper/swiper-bundle.min.css"
    />

    <!-- Demo styles -->
 <link rel="stylesheet" href="{% static 'css/swp.css' %}">
  </head>

  <body>
          <!-- Swiper start ============= -->
        <!-- Swiper -->

        <div class="box_xx" >
            <div class="swiper mySwiper">
          <div class="swiper-wrapper">
              {% for x in tt %}
            <div class="swiper-slide">

                      <div class="gsm-box" onclick="location.href='{% url  'list:sub_1' x.title %}';">
            <div class="icon"><img src={{x.icon.url}} loading="lazy" alt="" class="image-2"></div>
            <div class="icontext">
              <div class="text-block-8">{{x.title}} </div>
            </div>
          </div>
            </div>
                  {%endfor%}
          </div>
          <div class="swiper-pagination"></div>
        </div>

        <!-- Swiper JS -->
        <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
        <script src="{% static 'js/swp.js' %}" ></script>
        <!-- Initialize Swiper -->
          <!-- Swiper end ============== -->
              </div>
  <div class="b7r-section-a8sam wf-section">
<!--    <div class="genral-gsm">-->
<!--      <div class="h1-br" >-->
<!--        <h1 class="heading-4">بحري</h1><img src="{% static 'images/wave.svg' %}" loading="lazy" alt="" class="image-3">-->
<!--      </div>-->
<!--      <div class="h1-br">-->
<!--        <h1 class="heading-4">بري</h1><img src="{% static 'images/beach-chair.svg' %}" loading="lazy" alt="" class="image-3">-->
<!--      </div>-->
<!--    </div>-->
<!--    <div class="parter"></div>-->
<!--    <div class="a8sam-boxes">-->


    <div   onclick="location.href='{% url 'list:create_ad'%}';" style="cursor: pointer;"  class="add-your-ad">
      <div class="addd-text">   اضف اعلانك  </div>  <i class="far fa-plus-square"></i>
    </div>

  </div>

      	{% for x in ad%}
        <div class="add-container">
            <div  class="addbox" onclick="location.href='{% url 'list:details' x.id %}';" style="cursor: pointer;" >
      <div class="pic"><img src="" loading="lazy" width="270" sizes="(max-width: 479px) 98vw, (max-width: 767px) 166.203125px, 209.40625px" srcset="{{x.image.url}}" alt="" class="image"></div>
      <div class="add-detail">
        <div class="box-sec1">
         <div class="ad_name" >  {{x.title}} </div>

        </div>
        <div class="box-sec2">
          <div class="jeddah-text">{{x.city}} </div>
<!--          <div class="ratting">ratting</div>-->
        </div>
        <div class="box-sec3">
          <div class="text-block-7">{{x.username}}</div>
          <div class="add-box-pricebox">
            <div class="addbox-price"> {{x.price}} </div>
            <div class="text-block-6"> ريال</div>
          </div>
        </div>
      </div>

    </div>
        </div>


        {%endfor%}
  </div>
{% endblock body %}

adds/templates/list2.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
<html>

<div id="add-box-list" class="add-box-list">
	{% for x in ad %}
	<div id="add-box" class="add_box">
		<svg class="add-box-back">
			<rect id="add-box-back" rx="33" ry="33" x="0" y="0" width="1022" height="201">
			</rect>
		</svg>
		<div id="add-name">
			<span>{{x.title}}</span>
		</div>
		<img id="add-pic" src="{{x.image.url}}">

		<div id="add-cy">
			<span>جدة</span>
		</div>
		<div id="ratting">
			<span>7 / 10</span>
		</div>
		<div id="ratting-t">
			<span>التقييم</span>
		</div>
		<div id="price">
			<span> {{x.price}}  </span>
		</div>
		<div id="price-d">
			<span>  ريال</span>
		</div>
	</div>
		 {%endfor%}
           </div>






     <html/>
{% endblock body %}

templates/base.html
{% load static %}


<!DOCTYPE html><!--  This site was created in Webflow. http://www.webflow.com  -->
<!--  Last Published: Fri Aug 27 2021 19:20:25 GMT+0000 (Coordinated Universal Time)  -->
<html data-wf-page="6123e0de59b51973e0e2be7a" data-wf-site="6123e0de59b5192e0de2be79">

<head>
    <link href="{% static 'css/register.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet" type="text/css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/js/bootstrap.bundle.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" type="text/javascript"></script>
  <meta charset="utf-8">
  <title>Rehlaty</title>
  <meta content="width=device-width, initial-scale=1" name="viewport">
  <meta content="Webflow" name="generator">

  <link href="{% static 'css/normalize.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet" type="text/css">

  <link href="{% static 'css/all.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'css/webflow.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'css/rehlaty.webflow.css' %}" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" type="text/javascript"></script>
  <script type="text/javascript">WebFont.load({  google: {    families: ["Cairo:200,300,regular,600,700,900:arabic,latin,latin-ext"]  }});</script>
  <!-- [if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js" type="text/javascript"></script><![endif] -->
  <script type="text/javascript">!function(o,c){var n=c.documentElement,t=" w-mod-";n.className+=t+"js",("ontouchstart"in o||o.DocumentTouch&&c instanceof DocumentTouch)&&(n.className+=t+"touch")}(window,document);</script>
  <link href="{% static 'images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">
  <link href="{% static 'images/webclip.png' %"} rel="apple-touch-icon">
  <style>

      .bb {
        position: relative;
        height: 100%;
      }

      .bb {
        background: #eee;
        font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
        font-size: 14px;
        color: #000;
        margin: 0;
        padding: 0;
      }

      .swiper {
        width: 100%;
        height: 100%;
      }

      .swiper-slide {
        text-align: center;
        font-size: 18px;
        background: #fff;

        /* Center slide text vertically */
        display: -webkit-box;
        display: -ms-flexbox;
        display: -webkit-flex;
        display: flex;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        -webkit-justify-content: center;
        justify-content: center;
        -webkit-box-align: center;
        -ms-flex-align: center;
        -webkit-align-items: center;
        align-items: center;
      }

      .swiper-slide img {
        display: block;
        width: 100%;
        height: 100%;
        object-fit: cover;
      }
    </style>
</head>
<body class="body">
  <div data-collapse="medium" data-animation="over-right" data-duration="400" role="banner" class="navbar w-nav">
    <div class="container w-container">
      <a href="#" class="brand w-nav-brand">
        <h1 onclick="location.href='{% url 'list:list'%}';" style="cursor: pointer;" class="heading">رحلتي</h1>
      </a>
      <nav role="navigation" class="w-nav-menu">
           {% if request.user.is_authenticated %}
        <a href="{% url 'accounts:myaccount'%}" class="nav-link w-nav-link">مرحبا, {{request.user}} </a>
        {% else %}
        {% endif %}
                   {% if request.user.is_authenticated %}
        <a href="{% url 'list:create_ad' %}" class="nav-link w-nav-link">اضافة اعلان </a>
        {% else %}
        {% endif %}

        <a href="{% url 'list:list' %}" class="nav-link w-nav-link">الرئيسية</a>
        <a href="{% url 'list:sections' %}" class="nav-link w-nav-link">الاقسام </a>
        <a href="#" class="nav-link w-nav-link">المفضلة</a>
        {% if request.user.is_authenticated %}

        <a href="{% url 'accounts:logout' %}" class="nav-link w-nav-link">تسجيل خروج </a>

        {% else %}
         <a href="{% url 'accounts:login' %}" class="nav-link w-nav-link">تسجيل دخول </a>
        {% endif %}


      </nav>
      <div class="w-nav-button">
        <div data-w-id="9ec6dfca-75e8-109c-9ba1-f42f13254a11" class="hamburger-menu-hm8 w-nav-button">
          <div class="top-bar-hm8"></div>
          <div class="middle-bar-hm8"></div>
          <div class="bottom-bar-hm8"></div>
          <div class="cross-bar-1-hm8"></div>
          <div class="cross-bar-2-hm8"></div>
        </div>
      </div>
    </div>
  </div>

  	{% block body %}
    {% endblock body %}
  <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=6123e0de59b5192e0de2be79" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="{% static 'js/webflow.js' %}" type="text/javascript"></script>
  <!-- [if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif] -->




</body>

</html>

templates/myadds.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
     <link href="{% static 'css/myaccount.css' %}" rel="stylesheet" type="text/css">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>حسابي</title>
</head>
<body>
<div class="container">

         <div class="row">
         <div class="col-sm d-flex justify-content-center  " onclick="location.href='{% url 'accounts:myaccount'%}';" >
             <button type="button" class="btn btn-light rbox"><i class="fas fa-address-card"></i>   معلومات الحساب   </button>

         </div>
           <div class="col-sm d-flex justify-content-center  " onclick="location.href='{% url 'accounts:myadds'%}';" style="cursor: pointer;"  >
             <button type="button" class="btn btn-light rbox"><i class="fas fa-ad"></i>  الإعلانات   </button>

         </div>


</div>


      	{% for x in ad%}
        <div class="add-container">
            <div  class="addbox" onclick="location.href='{% url 'list:details' x.id %}';" style="cursor: pointer;" >
      <div class="pic"><img src="" loading="lazy" width="270" sizes="(max-width: 479px) 98vw, (max-width: 767px) 166.203125px, 209.40625px" srcset="{{x.image.url}}" alt="" class="image"></div>
      <div class="add-detail">
        <div class="box-sec1">
         <div class="ad_name" >  {{x.title}} </div>

        </div>
        <div class="box-sec2">
          <div class="jeddah-text">{{x.city}} </div>
<!--          <div class="ratting">ratting</div>-->
        </div>
        <div class="box-sec3">
          <div class="text-block-7">{{x.username}}</div>
          <div class="add-box-pricebox">
            <div class="addbox-price"> {{x.price}} </div>
            <div class="text-block-6"> ريال</div>
          </div>
        </div>
      </div>


    </div>
            <div class="add_op">
                <button type="button" class="btn btn-danger">حذف</button>
                <button type="button" class="btn btn-warning" onclick="location.href='{% url 'list:update_add' x.id %}';" style="cursor: pointer;" >تعديل</button>
                <button type="button" class="btn btn-info">تحديث</button>

                </div>
        </div>


        {%endfor%}
  </div>

 </div>
</body>
</html>
{% endblock body %}